### DISCUSSION TITLE
Games "Chorus" is missing Linux savegames

### DISCUSSION THREAD

**Discussion by nicolasnobelis** [mtkennerly/ludusavi-manifest#55] [Q&A] [answered]
PCGW lists:

![image](https://github.com/user-attachments/assets/9a99dc1c-03c5-480b-bdbf-0b9ae628562e)

https://www.pcgamingwiki.com/wiki/Chorus

But Ludusavi has only the Windows entry:
```
files:
    "<winLocalAppData>/SpacePrototype/Config/WindowsNoEditor":
      tags:
        - config
      when:
        - os: windows
    "<winLocalAppData>/SpacePrototype/SaveGames":
      tags:
        - save
      when:
        - os: windows
```

Running a Ludusavi Preview does not find the saves on Linux.
