### ISSUE TITLE
<storeUserId>/<user-id> not detected for Divinity: Original Sin II - Definitive Edition

### ISSUE THREAD

**Issue by redactedscribe** [mtkennerly/ludusavi-manifest#14]
[Divinity: Original Sin II - Definitive Edition](https://www.pcgamingwiki.com/wiki/Divinity:_Original_Sin_II_-_Definitive_Edition).

For example, should be detecting `%USERPROFILE%\Documents\Larian Studios\Divinity Original Sin 2 Definitive Edition\PlayerProfiles\<some_user_defined_string>\Savegames\` but isn't.

The issue appears to be that `<user-id>` on PCGW is defined as "The user ID or profile name (specific to your account or computer)" (if you mouseover "\<user-id\>"), but Ludusavi thinks of it differently as evidenced by its own placeholder named `<storeUserId>` as seen when looking the custom rule made for the game after pressing Customize.

In this game's case, `<user-id>` is just a profile name used within the game created by the player, not an ID from any particular store. Because of this, Ludusavi should probably just think of PCGW's `<user-id>` as `*`. Or perhaps `<user-id>` is being used incorrectly on PCGW in this case? Depends on the interpretation of the definition I quoted above.

Thanks.

**Comment by mtkennerly** [comment]
Ludusavi does indeed interpret `<storeUserId>` as `*`, so this should work. I don't own the game, but if I manually create something there, it's recognized:

```
$ cargo run -- backup --preview 'Divinity: Original Sin II - Definitive Edition'
Divinity: Original Sin II - Definitive Edition [0 B]:
  - C:/Users/mtken/Documents/Larian Studios/Divinity Original Sin 2 Definitive Edition/PlayerProfiles/123/Savegames/asd.txt
```

I do see that one entry uses `PlayerProfile` while the others use `PlayerProfiles`. Could you double check if that's the only typo on the wiki? [Larian's website](https://larian.com/support/faqs/how-to-transfer-saves-to-from-ipad_69) and [this Reddit comment](https://www.reddit.com/r/DivinityOriginalSin/comments/fzi2gk/comment/fn4mig2/?utm_source=share&utm_medium=web2x&context=3) show `Player Profiles` with a space, for example.

**Comment by redactedscribe** [comment]
On my system, it's definitely `%USERPROFILE%\Documents\Larian Studios\Divinity Original Sin 2 Definitive Edition\PlayerProfiles\...` with an 's'.

I can only presume that `\Player Profiles\` is likely wrong, despite being on the official website. This is because, for both Windows and macOS, they include a colon ("... 2: Definitive ...") in the same paths which isn't a valid character for folder names on both OSes, so that would be the second error.

Concerning Windows, the manifest shows:

```yaml
<winDocuments>/Larian Studios/Divinity Original Sin 2 Definitive Edition/PlayerProfile/<storeUserId>:
  tags:
    - config
  when:
    - os: windows
<winDocuments>/Larian Studios/Divinity Original Sin 2 Definitive Edition/PlayerProfiles/<storeUserId>/Savegames:
  tags:
    - save
  when:
    - os: windows
```

One path without the 's' (top) and one with (bottom). Neither of the paths match despite the bottom one being correct, at least for my system. I will correct the top path on PCGW to include an 's'.

The only match I get in Ludusavi is for the other config path:

```yaml
<winDocuments>/Larian Studios/Divinity Original Sin 2 Definitive Edition/graphicSettings.lsx:
  tags:
    - config
  when:
    - os: windows
```
