### ISSUE TITLE
Handle GOG game bundles like Bioshock 2

### ISSUE THREAD

**Issue by sluedecke** [mtkennerly/ludusavi-manifest#18]
Follow up on #16:

But as life isn't, this isn't without exceptions, e.g. "Bioshock 2" comes as a bundle on GOG.com:

* GOG product ID is 1111208428
* such is the "gogcom id" on PCGW
* but gog_store/library,json lists it twice with app_name "1806891286" and app_name "1482265668"
* in fact 1111208428 is a bundle on gog which includes "Bioshock 2 Classic" (1806891286) and "Bioshock 2 Remastered" (1482265668)

This might not be a big issue or an issue at all, but it is worth having a closer look.

**Comment by mtkennerly** [comment]
It's not ideal, but we could add it to `data/manifest-override.yaml`. For example:

```yaml
BioShock 2:
  gog:
    id: 1806891286
BioShock 2 Remastered:
  gog:
    id: 1482265668
```

Then we would just need to handle it in `updateGames` (manifest.ts).
