### ISSUE TITLE
[BUG] MGS2 & MGS3 not being detected

### ISSUE THREAD

**Issue by BloodShed-Oni** [mtkennerly/ludusavi-manifest#33]
I'm unsure if I'm supposed to post the issue here or for Ludusavi, since I don't know where the problem lies.

'Metal Gear Solid 2: Sons of Liberty - Master Collection Version' and 'Metal Gear Solid 3: Snake Eater - Master Collection Version' aren't being detected in Ludusavi.

I've checked the manifest.yaml and PCGamingWiki and the entries look correct

PCgamingWiki entries

Metal Gear Solid 2: Sons of Liberty - Master Collection Version
```
<path-to-game>\mgs2_savedata_win\<user-id>\
```

Metal Gear Solid 3: Snake Eater - Master Collection Version
```
<path-to-game>\mgs3_savedata_win\<user-id>\
```

manifest.yaml entries
```
'Metal Gear Solid 2: Sons of Liberty - Master Collection Version':
  files:
    <base>/mgs2_savedata_win/<storeUserId>:
      tags:
        - save
      when:
        - os: windows
    <base>/mgs2_savedata_win/<storeUserId>/launcher:
      tags:
        - config
      when:
        - os: windows
  steam:
    id: 2131640
'Metal Gear Solid 3: Snake Eater - Master Collection Version':
  files:
    <base>/mgs3_savedata_win/<storeUserId>:
      tags:
        - save
      when:
        - os: windows
    <base>/mgs3_savedata_win/<storeUserId>/launcher:
      tags:
        - config
      when:
        - os: windows
  steam:
    id: 2131650
```

For reference the save locations on my system

Metal Gear Solid 2: Sons of Liberty - Master Collection Version
D:\Steam\steamapps\common\MGS2\mgs2_savedata_win\76561197960485586

Metal Gear Solid 3: Snake Eater - Master Collection Version
D:\Steam\steamapps\common\MGS3\mgs3_savedata_win\76561197960485586
