### ISSUE TITLE
The data in the manifest seems to think the entirety of Paladins is the config files.

### ISSUE THREAD

**Issue by ThePenguinPrince** [mtkennerly/ludusavi-manifest#35]
Ludusavi tried to create a 30gb backup for Paladins: Champions of the Realm.
Relevant snippet:
```
"Paladins: Champions of the Realm":
  files:
    "<base>/ChaosGame":
      tags:
        - config
      when:
        - os: windows
    "<winDocuments>/My Games/Paladins/ChaosGame/Config":
      tags:
        - config
      when:
        - os: windows
```
Should probably be:
"\<base\>/ChaosGame/Config"
