### ISSUE TITLE
Files for Vampyr removed from manifest

### ISSUE THREAD

**Issue by sharkusmanch** [mtkennerly/ludusavi-manifest#38]
Looks like the save files for Vampyr have been removed from the manifest for some reason. The save data paths are still present in the [PCGamingWiki article](https://www.pcgamingwiki.com/wiki/Vampyr)

There have been some edits to the article between the two manifest dates I checked, but nothing touching the save data portion.

Current entry for Vampyr:
```
Vampyr:
  gog:
    id: 2098644729
  id:
    gogExtra:
      - 1949020249
    steamExtra:
      - 728850
  installDir:
    Vampyr: {}
  launch:
    "<base>/AVGame/Binaries/Win64/AVGame-Win64-Shipping.exe":
      - when:
          - bit: 64
            os: windows
            store: steam
        workingDir: "<base>/AVGame/Binaries/Win64"
  steam:
    id: 427290
```

[Entry from December 4 (arbitrarily checked date)](https://raw.githubusercontent.com/mtkennerly/ludusavi-manifest/a1ee065e0be6285459045a746ac538bf870d3ee1/data/manifest.yaml):
```
Vampyr:
  files:
    "<winLocalAppData>/AVGame/Saved/Config/WindowsNoEditor":
      tags:
        - config
      when:
        - os: windows
    "<winLocalAppData>/AVGame/Saved/SaveGames":
      tags:
        - save
      when:
        - os: windows
    "<winLocalAppData>/Packages/FocusHomeInteractiveSA.VAMPYR_4hny5m903y3g0/LocalCache/Local/AVGame/Saved/Config/WindowsNoEditor":
      tags:
        - config
      when:
        - os: windows
          store: microsoft
    "<winLocalAppData>/Packages/FocusHomeInteractiveSA.VAMPYR_4hny5m903y3g0/LocalCache/Local/AVGame/Saved/SaveGames":
      tags:
        - save
      when:
        - os: windows
          store: microsoft
  gog:
    id: 2098644729
  id:
    gogExtra:
      - 1949020249
    steamExtra:
      - 728850
  installDir:
    Vampyr: {}
  launch:
    "<base>/AVGame/Binaries/Win64/AVGame-Win64-Shipping.exe":
      - when:
          - bit: 64
            os: windows
            store: steam
        workingDir: "<base>/AVGame/Binaries/Win64"
  steam:
    id: 427290
```
