### ISSUE TITLE
Stale/Incorrect data for Nevsky Run

### ISSUE THREAD

**Issue by sharkusmanch** [mtkennerly/ludusavi-manifest#41]
After re-installing Kingdom Come Deliverance, ludusavi is now detecting save data for `Nevsky_Run`

https://www.pcgamingwiki.com/wiki/Nevsky_Run

Not sure how the paths were ever added. Looking at the PCGamingWiki article history, I don't see any additions of the save paths
```
Nevsky Run:
  files:
    "<home>/Saved Games/kingdomcome/kingdomcome/saves/playline0":
      when:
        - os: windows
          store: steam
    "<home>/Saved Games/kingdomcome/saves/playline0":
      when:
        - os: windows
          store: steam
  installDir:
    Secret_Girl: {}
  launch:
    "<base>/Secret_Girl/SteamG/Binaries/Win64/SteamG-Win64-Shipping.exe":
      - when:
          - bit: 64
            os: windows
            store: steam
  steam:
    id: 946210
```
