### ISSUE TITLE
Rocksmith+ definition in the manifest isn't specific enough

### ISSUE THREAD

**Issue by davidhesselbom** [mtkennerly/ludusavi-manifest#5]
This is in data/manifest.yaml:

```yml
Rocksmith+:
  files:
    <winDocuments>/My Games:
      tags:
        - config
      when:
        - os: windows
```

I don't have this game installed on my machine, but Ludusavi "detects" it anyway and makes a huge backup for it containing data from every game in that folder. I suspect the definition shouldn't actually include all of `/My games`? Sorry if I'm barking up the wrong tree...
