### ISSUE TITLE
Dead Cells - missing

### ISSUE THREAD

**Issue by sluedecke** [mtkennerly/ludusavi-manifest#8]
Somehow I could not find dead cells in the manifest although it exists here:  https://www.pcgamingwiki.com/wiki/Dead_Cells 

How can I best get it added to the manifest?

**Comment by mtkennerly** [comment]
Hi! Dead Cells is already in the manifest (between `Dead Castle` and `Dead Climb`):

> <img width="236" alt="image" src="https://user-images.githubusercontent.com/4934192/184452100-cd9b3b33-3aa9-4653-8baf-ad21e62999b1.png">

Could you please confirm where you're checking? Or if the issue is just that Ludusavi isn't finding your saves for it, then could you show me your Ludusavi backup config?

**Comment by sluedecke** [comment]
I looked in this repository but obviously missed it.  On my system, `~/.config/ludusavi/manifest.yaml`  contains an entry for Dead Cells, but ludusavi 0.10.0 (arch linux) does not backup the game.  My save files are found here:  `~/Games/Dead Cells/game/save` with `~/Games` being the root folder for my GOG games.  Other games in this folder (e.g. Pillars of Eternity) seem to be backed up correctly.

This is my `~/.config/ludusavi/config.yaml`

```
---
manifest:
  url: "https://raw.githubusercontent.com/mtkennerly/ludusavi-manifest/master/data/manifest.yaml"
  etag: "\"c6046cc8011fc8b38ff2f7405666d98ec840f0fb0b72a971cf44a763dc8907fa\""
roots:
  - path: ~/.steam/steam
    store: steam
  - path: ~/Games
    store: gog
backup:
  path: /home/USERGames/00-savegames/0-ludusavi-backup
  ignoredGames: []
  merge: false
  filter: {}
restore:
  path: /home/USER/ludusavi-backup
  ignoredGames: []
  redirects: []
customGames: []
```

Any idea what I could do?
